//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WinClientSQLUpdateDelete.WS_SQLUpdateDelete {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSQLUpdateDeleteSoap", Namespace="http://www.ieee.org/9780521712354/")]
    public partial class WebServiceSQLUpdateDelete : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SQLUpdateSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSQLCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSQLCourseDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SQLDeleteSPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceSQLUpdateDelete() {
            this.Url = global::WinClientSQLUpdateDelete.Properties.Settings.Default.WinClientSQLUpdateDelete_WS_SQLUpdateDelete_WebServiceSQLUpdateDelete;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SQLUpdateSPCompletedEventHandler SQLUpdateSPCompleted;
        
        /// <remarks/>
        public event GetSQLCourseCompletedEventHandler GetSQLCourseCompleted;
        
        /// <remarks/>
        public event GetSQLCourseDetailCompletedEventHandler GetSQLCourseDetailCompleted;
        
        /// <remarks/>
        public event SQLDeleteSPCompletedEventHandler SQLDeleteSPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/SQLUpdateSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLBase SQLUpdateSP(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            object[] results = this.Invoke("SQLUpdateSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll});
            return ((SQLBase)(results[0]));
        }
        
        /// <remarks/>
        public void SQLUpdateSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            this.SQLUpdateSPAsync(FacultyName, CourseID, Course, Schedule, Classroom, Credit, Enroll, null);
        }
        
        /// <remarks/>
        public void SQLUpdateSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll, object userState) {
            if ((this.SQLUpdateSPOperationCompleted == null)) {
                this.SQLUpdateSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSQLUpdateSPOperationCompleted);
            }
            this.InvokeAsync("SQLUpdateSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll}, this.SQLUpdateSPOperationCompleted, userState);
        }
        
        private void OnSQLUpdateSPOperationCompleted(object arg) {
            if ((this.SQLUpdateSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SQLUpdateSPCompleted(this, new SQLUpdateSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetSQLCourse", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLBase GetSQLCourse(string FacultyName) {
            object[] results = this.Invoke("GetSQLCourse", new object[] {
                        FacultyName});
            return ((SQLBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQLCourseAsync(string FacultyName) {
            this.GetSQLCourseAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetSQLCourseAsync(string FacultyName, object userState) {
            if ((this.GetSQLCourseOperationCompleted == null)) {
                this.GetSQLCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQLCourseOperationCompleted);
            }
            this.InvokeAsync("GetSQLCourse", new object[] {
                        FacultyName}, this.GetSQLCourseOperationCompleted, userState);
        }
        
        private void OnGetSQLCourseOperationCompleted(object arg) {
            if ((this.GetSQLCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQLCourseCompleted(this, new GetSQLCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetSQLCourseDetail", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLBase GetSQLCourseDetail(string CourseID) {
            object[] results = this.Invoke("GetSQLCourseDetail", new object[] {
                        CourseID});
            return ((SQLBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQLCourseDetailAsync(string CourseID) {
            this.GetSQLCourseDetailAsync(CourseID, null);
        }
        
        /// <remarks/>
        public void GetSQLCourseDetailAsync(string CourseID, object userState) {
            if ((this.GetSQLCourseDetailOperationCompleted == null)) {
                this.GetSQLCourseDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQLCourseDetailOperationCompleted);
            }
            this.InvokeAsync("GetSQLCourseDetail", new object[] {
                        CourseID}, this.GetSQLCourseDetailOperationCompleted, userState);
        }
        
        private void OnGetSQLCourseDetailOperationCompleted(object arg) {
            if ((this.GetSQLCourseDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQLCourseDetailCompleted(this, new GetSQLCourseDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/SQLDeleteSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLBase SQLDeleteSP(string CourseID) {
            object[] results = this.Invoke("SQLDeleteSP", new object[] {
                        CourseID});
            return ((SQLBase)(results[0]));
        }
        
        /// <remarks/>
        public void SQLDeleteSPAsync(string CourseID) {
            this.SQLDeleteSPAsync(CourseID, null);
        }
        
        /// <remarks/>
        public void SQLDeleteSPAsync(string CourseID, object userState) {
            if ((this.SQLDeleteSPOperationCompleted == null)) {
                this.SQLDeleteSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSQLDeleteSPOperationCompleted);
            }
            this.InvokeAsync("SQLDeleteSP", new object[] {
                        CourseID}, this.SQLDeleteSPOperationCompleted, userState);
        }
        
        private void OnSQLDeleteSPOperationCompleted(object arg) {
            if ((this.SQLDeleteSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SQLDeleteSPCompleted(this, new SQLDeleteSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class SQLBase {
        
        private bool sQLOKField;
        
        private string sQLErrorField;
        
        private string facultyIDField;
        
        private string[] courseIDField;
        
        private string courseField;
        
        private string scheduleField;
        
        private string classroomField;
        
        private int creditField;
        
        private int enrollmentField;
        
        /// <remarks/>
        public bool SQLOK {
            get {
                return this.sQLOKField;
            }
            set {
                this.sQLOKField = value;
            }
        }
        
        /// <remarks/>
        public string SQLError {
            get {
                return this.sQLErrorField;
            }
            set {
                this.sQLErrorField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyID {
            get {
                return this.facultyIDField;
            }
            set {
                this.facultyIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
            }
        }
        
        /// <remarks/>
        public string Classroom {
            get {
                return this.classroomField;
            }
            set {
                this.classroomField = value;
            }
        }
        
        /// <remarks/>
        public int Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public int Enrollment {
            get {
                return this.enrollmentField;
            }
            set {
                this.enrollmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SQLUpdateSPCompletedEventHandler(object sender, SQLUpdateSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SQLUpdateSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SQLUpdateSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSQLCourseCompletedEventHandler(object sender, GetSQLCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQLCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQLCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSQLCourseDetailCompletedEventHandler(object sender, GetSQLCourseDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQLCourseDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQLCourseDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SQLDeleteSPCompletedEventHandler(object sender, SQLDeleteSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SQLDeleteSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SQLDeleteSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLBase)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591