//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WinClientOracleInsert.WS_OracleInsert {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceOracleInsertSoap", Namespace="http://www.ieee.org/9780521712354/")]
    public partial class WebServiceOracleInsert : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetOracleInsertSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleInsertCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback OracleInsertDataSetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceOracleInsert() {
            this.Url = global::WinClientOracleInsert.Properties.Settings.Default.WinClientOracleInsert_WS_OracleInsert_WebServiceOracleInsert;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetOracleInsertSPCompletedEventHandler SetOracleInsertSPCompleted;
        
        /// <remarks/>
        public event GetOracleInsertCompletedEventHandler GetOracleInsertCompleted;
        
        /// <remarks/>
        public event GetOracleInsertCourseCompletedEventHandler GetOracleInsertCourseCompleted;
        
        /// <remarks/>
        public event OracleInsertDataSetCompletedEventHandler OracleInsertDataSetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/SetOracleInsertSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleInsertBase SetOracleInsertSP(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            object[] results = this.Invoke("SetOracleInsertSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll});
            return ((OracleInsertBase)(results[0]));
        }
        
        /// <remarks/>
        public void SetOracleInsertSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            this.SetOracleInsertSPAsync(FacultyName, CourseID, Course, Schedule, Classroom, Credit, Enroll, null);
        }
        
        /// <remarks/>
        public void SetOracleInsertSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll, object userState) {
            if ((this.SetOracleInsertSPOperationCompleted == null)) {
                this.SetOracleInsertSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetOracleInsertSPOperationCompleted);
            }
            this.InvokeAsync("SetOracleInsertSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll}, this.SetOracleInsertSPOperationCompleted, userState);
        }
        
        private void OnSetOracleInsertSPOperationCompleted(object arg) {
            if ((this.SetOracleInsertSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetOracleInsertSPCompleted(this, new SetOracleInsertSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleInsert", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleInsertBase GetOracleInsert(string FacultyName) {
            object[] results = this.Invoke("GetOracleInsert", new object[] {
                        FacultyName});
            return ((OracleInsertBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleInsertAsync(string FacultyName) {
            this.GetOracleInsertAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetOracleInsertAsync(string FacultyName, object userState) {
            if ((this.GetOracleInsertOperationCompleted == null)) {
                this.GetOracleInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleInsertOperationCompleted);
            }
            this.InvokeAsync("GetOracleInsert", new object[] {
                        FacultyName}, this.GetOracleInsertOperationCompleted, userState);
        }
        
        private void OnGetOracleInsertOperationCompleted(object arg) {
            if ((this.GetOracleInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleInsertCompleted(this, new GetOracleInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleInsertCourse", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleInsertBase GetOracleInsertCourse(string CourseID) {
            object[] results = this.Invoke("GetOracleInsertCourse", new object[] {
                        CourseID});
            return ((OracleInsertBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleInsertCourseAsync(string CourseID) {
            this.GetOracleInsertCourseAsync(CourseID, null);
        }
        
        /// <remarks/>
        public void GetOracleInsertCourseAsync(string CourseID, object userState) {
            if ((this.GetOracleInsertCourseOperationCompleted == null)) {
                this.GetOracleInsertCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleInsertCourseOperationCompleted);
            }
            this.InvokeAsync("GetOracleInsertCourse", new object[] {
                        CourseID}, this.GetOracleInsertCourseOperationCompleted, userState);
        }
        
        private void OnGetOracleInsertCourseOperationCompleted(object arg) {
            if ((this.GetOracleInsertCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleInsertCourseCompleted(this, new GetOracleInsertCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/OracleInsertDataSet", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OracleInsertDataSet(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            object[] results = this.Invoke("OracleInsertDataSet", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OracleInsertDataSetAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            this.OracleInsertDataSetAsync(FacultyName, CourseID, Course, Schedule, Classroom, Credit, Enroll, null);
        }
        
        /// <remarks/>
        public void OracleInsertDataSetAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll, object userState) {
            if ((this.OracleInsertDataSetOperationCompleted == null)) {
                this.OracleInsertDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOracleInsertDataSetOperationCompleted);
            }
            this.InvokeAsync("OracleInsertDataSet", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll}, this.OracleInsertDataSetOperationCompleted, userState);
        }
        
        private void OnOracleInsertDataSetOperationCompleted(object arg) {
            if ((this.OracleInsertDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OracleInsertDataSetCompleted(this, new OracleInsertDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class OracleInsertBase {
        
        private bool oracleInsertOKField;
        
        private string oracleInsertErrorField;
        
        private string facultyIDField;
        
        private string[] courseIDField;
        
        private string courseField;
        
        private string scheduleField;
        
        private string classroomField;
        
        private int creditField;
        
        private int enrollmentField;
        
        /// <remarks/>
        public bool OracleInsertOK {
            get {
                return this.oracleInsertOKField;
            }
            set {
                this.oracleInsertOKField = value;
            }
        }
        
        /// <remarks/>
        public string OracleInsertError {
            get {
                return this.oracleInsertErrorField;
            }
            set {
                this.oracleInsertErrorField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyID {
            get {
                return this.facultyIDField;
            }
            set {
                this.facultyIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
            }
        }
        
        /// <remarks/>
        public string Classroom {
            get {
                return this.classroomField;
            }
            set {
                this.classroomField = value;
            }
        }
        
        /// <remarks/>
        public int Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public int Enrollment {
            get {
                return this.enrollmentField;
            }
            set {
                this.enrollmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SetOracleInsertSPCompletedEventHandler(object sender, SetOracleInsertSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetOracleInsertSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetOracleInsertSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleInsertBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleInsertBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleInsertCompletedEventHandler(object sender, GetOracleInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleInsertBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleInsertBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleInsertCourseCompletedEventHandler(object sender, GetOracleInsertCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleInsertCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleInsertCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleInsertBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleInsertBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void OracleInsertDataSetCompletedEventHandler(object sender, OracleInsertDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OracleInsertDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OracleInsertDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591