//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WinClientOracleSelect.WS_OracleSelect {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceOracleSelectSoap", Namespace="http://www.ieee.org/9780521712354/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleSelectBase))]
    public partial class WebServiceOracleSelect : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOracleSelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleSelectSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleSelectDataSetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceOracleSelect() {
            this.Url = global::WinClientOracleSelect.Properties.Settings.Default.WinClientOracleSelect_WS_OracleSelect_WebServiceOracleSelect;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOracleSelectCompletedEventHandler GetOracleSelectCompleted;
        
        /// <remarks/>
        public event GetOracleSelectSPCompletedEventHandler GetOracleSelectSPCompleted;
        
        /// <remarks/>
        public event GetOracleSelectDataSetCompletedEventHandler GetOracleSelectDataSetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleSelect", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleSelectResult GetOracleSelect(string FacultyName) {
            object[] results = this.Invoke("GetOracleSelect", new object[] {
                        FacultyName});
            return ((OracleSelectResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleSelectAsync(string FacultyName) {
            this.GetOracleSelectAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetOracleSelectAsync(string FacultyName, object userState) {
            if ((this.GetOracleSelectOperationCompleted == null)) {
                this.GetOracleSelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleSelectOperationCompleted);
            }
            this.InvokeAsync("GetOracleSelect", new object[] {
                        FacultyName}, this.GetOracleSelectOperationCompleted, userState);
        }
        
        private void OnGetOracleSelectOperationCompleted(object arg) {
            if ((this.GetOracleSelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleSelectCompleted(this, new GetOracleSelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleSelectSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleSelectResult GetOracleSelectSP(string FacultyName) {
            object[] results = this.Invoke("GetOracleSelectSP", new object[] {
                        FacultyName});
            return ((OracleSelectResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleSelectSPAsync(string FacultyName) {
            this.GetOracleSelectSPAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetOracleSelectSPAsync(string FacultyName, object userState) {
            if ((this.GetOracleSelectSPOperationCompleted == null)) {
                this.GetOracleSelectSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleSelectSPOperationCompleted);
            }
            this.InvokeAsync("GetOracleSelectSP", new object[] {
                        FacultyName}, this.GetOracleSelectSPOperationCompleted, userState);
        }
        
        private void OnGetOracleSelectSPOperationCompleted(object arg) {
            if ((this.GetOracleSelectSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleSelectSPCompleted(this, new GetOracleSelectSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleSelectDataSet", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOracleSelectDataSet(string FacultyName) {
            object[] results = this.Invoke("GetOracleSelectDataSet", new object[] {
                        FacultyName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleSelectDataSetAsync(string FacultyName) {
            this.GetOracleSelectDataSetAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetOracleSelectDataSetAsync(string FacultyName, object userState) {
            if ((this.GetOracleSelectDataSetOperationCompleted == null)) {
                this.GetOracleSelectDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleSelectDataSetOperationCompleted);
            }
            this.InvokeAsync("GetOracleSelectDataSet", new object[] {
                        FacultyName}, this.GetOracleSelectDataSetOperationCompleted, userState);
        }
        
        private void OnGetOracleSelectDataSetOperationCompleted(object arg) {
            if ((this.GetOracleSelectDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleSelectDataSetCompleted(this, new GetOracleSelectDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class OracleSelectResult : OracleSelectBase {
        
        private string facultyIDField;
        
        private string facultyOfficeField;
        
        private string facultyPhoneField;
        
        private string facultyCollegeField;
        
        private string facultyTitleField;
        
        private string facultyEmailField;
        
        /// <remarks/>
        public string FacultyID {
            get {
                return this.facultyIDField;
            }
            set {
                this.facultyIDField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyOffice {
            get {
                return this.facultyOfficeField;
            }
            set {
                this.facultyOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyPhone {
            get {
                return this.facultyPhoneField;
            }
            set {
                this.facultyPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyCollege {
            get {
                return this.facultyCollegeField;
            }
            set {
                this.facultyCollegeField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyTitle {
            get {
                return this.facultyTitleField;
            }
            set {
                this.facultyTitleField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyEmail {
            get {
                return this.facultyEmailField;
            }
            set {
                this.facultyEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleSelectResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class OracleSelectBase {
        
        private bool oracleRequestOKField;
        
        private string oracleRequestErrorField;
        
        /// <remarks/>
        public bool OracleRequestOK {
            get {
                return this.oracleRequestOKField;
            }
            set {
                this.oracleRequestOKField = value;
            }
        }
        
        /// <remarks/>
        public string OracleRequestError {
            get {
                return this.oracleRequestErrorField;
            }
            set {
                this.oracleRequestErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleSelectCompletedEventHandler(object sender, GetOracleSelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleSelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleSelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleSelectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleSelectResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleSelectSPCompletedEventHandler(object sender, GetOracleSelectSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleSelectSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleSelectSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleSelectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleSelectResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleSelectDataSetCompletedEventHandler(object sender, GetOracleSelectDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleSelectDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleSelectDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591