//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WinClientOracleUpdateDelete.WS_OracleUD {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceOracleUpdateDeleteSoap", Namespace="http://www.ieee.org/9780521712354/")]
    public partial class WebServiceOracleUpdateDelete : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OracleUpdateSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOracleCourseDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback OracleDeleteSPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceOracleUpdateDelete() {
            this.Url = global::WinClientOracleUpdateDelete.Properties.Settings.Default.WinClientOracleUpdateDelete_WS_OracleUD_WebServiceOracleUpdateDelete;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OracleUpdateSPCompletedEventHandler OracleUpdateSPCompleted;
        
        /// <remarks/>
        public event GetOracleCourseCompletedEventHandler GetOracleCourseCompleted;
        
        /// <remarks/>
        public event GetOracleCourseDetailCompletedEventHandler GetOracleCourseDetailCompleted;
        
        /// <remarks/>
        public event OracleDeleteSPCompletedEventHandler OracleDeleteSPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/OracleUpdateSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleBase OracleUpdateSP(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            object[] results = this.Invoke("OracleUpdateSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll});
            return ((OracleBase)(results[0]));
        }
        
        /// <remarks/>
        public void OracleUpdateSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll) {
            this.OracleUpdateSPAsync(FacultyName, CourseID, Course, Schedule, Classroom, Credit, Enroll, null);
        }
        
        /// <remarks/>
        public void OracleUpdateSPAsync(string FacultyName, string CourseID, string Course, string Schedule, string Classroom, int Credit, int Enroll, object userState) {
            if ((this.OracleUpdateSPOperationCompleted == null)) {
                this.OracleUpdateSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOracleUpdateSPOperationCompleted);
            }
            this.InvokeAsync("OracleUpdateSP", new object[] {
                        FacultyName,
                        CourseID,
                        Course,
                        Schedule,
                        Classroom,
                        Credit,
                        Enroll}, this.OracleUpdateSPOperationCompleted, userState);
        }
        
        private void OnOracleUpdateSPOperationCompleted(object arg) {
            if ((this.OracleUpdateSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OracleUpdateSPCompleted(this, new OracleUpdateSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleCourse", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleBase GetOracleCourse(string FacultyName) {
            object[] results = this.Invoke("GetOracleCourse", new object[] {
                        FacultyName});
            return ((OracleBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleCourseAsync(string FacultyName) {
            this.GetOracleCourseAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetOracleCourseAsync(string FacultyName, object userState) {
            if ((this.GetOracleCourseOperationCompleted == null)) {
                this.GetOracleCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleCourseOperationCompleted);
            }
            this.InvokeAsync("GetOracleCourse", new object[] {
                        FacultyName}, this.GetOracleCourseOperationCompleted, userState);
        }
        
        private void OnGetOracleCourseOperationCompleted(object arg) {
            if ((this.GetOracleCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleCourseCompleted(this, new GetOracleCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetOracleCourseDetail", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleBase GetOracleCourseDetail(string CourseID) {
            object[] results = this.Invoke("GetOracleCourseDetail", new object[] {
                        CourseID});
            return ((OracleBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleCourseDetailAsync(string CourseID) {
            this.GetOracleCourseDetailAsync(CourseID, null);
        }
        
        /// <remarks/>
        public void GetOracleCourseDetailAsync(string CourseID, object userState) {
            if ((this.GetOracleCourseDetailOperationCompleted == null)) {
                this.GetOracleCourseDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleCourseDetailOperationCompleted);
            }
            this.InvokeAsync("GetOracleCourseDetail", new object[] {
                        CourseID}, this.GetOracleCourseDetailOperationCompleted, userState);
        }
        
        private void OnGetOracleCourseDetailOperationCompleted(object arg) {
            if ((this.GetOracleCourseDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleCourseDetailCompleted(this, new GetOracleCourseDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/OracleDeleteSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OracleBase OracleDeleteSP(string CourseID) {
            object[] results = this.Invoke("OracleDeleteSP", new object[] {
                        CourseID});
            return ((OracleBase)(results[0]));
        }
        
        /// <remarks/>
        public void OracleDeleteSPAsync(string CourseID) {
            this.OracleDeleteSPAsync(CourseID, null);
        }
        
        /// <remarks/>
        public void OracleDeleteSPAsync(string CourseID, object userState) {
            if ((this.OracleDeleteSPOperationCompleted == null)) {
                this.OracleDeleteSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOracleDeleteSPOperationCompleted);
            }
            this.InvokeAsync("OracleDeleteSP", new object[] {
                        CourseID}, this.OracleDeleteSPOperationCompleted, userState);
        }
        
        private void OnOracleDeleteSPOperationCompleted(object arg) {
            if ((this.OracleDeleteSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OracleDeleteSPCompleted(this, new OracleDeleteSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class OracleBase {
        
        private bool oracleOKField;
        
        private string oracleErrorField;
        
        private string facultyIDField;
        
        private string[] courseIDField;
        
        private string courseField;
        
        private string scheduleField;
        
        private string classroomField;
        
        private int creditField;
        
        private int enrollmentField;
        
        /// <remarks/>
        public bool OracleOK {
            get {
                return this.oracleOKField;
            }
            set {
                this.oracleOKField = value;
            }
        }
        
        /// <remarks/>
        public string OracleError {
            get {
                return this.oracleErrorField;
            }
            set {
                this.oracleErrorField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyID {
            get {
                return this.facultyIDField;
            }
            set {
                this.facultyIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] CourseID {
            get {
                return this.courseIDField;
            }
            set {
                this.courseIDField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string Schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
            }
        }
        
        /// <remarks/>
        public string Classroom {
            get {
                return this.classroomField;
            }
            set {
                this.classroomField = value;
            }
        }
        
        /// <remarks/>
        public int Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public int Enrollment {
            get {
                return this.enrollmentField;
            }
            set {
                this.enrollmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void OracleUpdateSPCompletedEventHandler(object sender, OracleUpdateSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OracleUpdateSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OracleUpdateSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleCourseCompletedEventHandler(object sender, GetOracleCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetOracleCourseDetailCompletedEventHandler(object sender, GetOracleCourseDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleCourseDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleCourseDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void OracleDeleteSPCompletedEventHandler(object sender, OracleDeleteSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OracleDeleteSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OracleDeleteSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleBase)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591