//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WinClientSQLSelect.WS_SQLSelect {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSQLSelectSoap", Namespace="http://www.ieee.org/9780521712354/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLSelectBase))]
    public partial class WebServiceSQLSelect : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSQLSelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSQLSelectSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSQLSelectDataSetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceSQLSelect() {
            this.Url = global::WinClientSQLSelect.Properties.Settings.Default.WinClientSQLSelect_WS_SQLSelect_WebServiceSQLSelect;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSQLSelectCompletedEventHandler GetSQLSelectCompleted;
        
        /// <remarks/>
        public event GetSQLSelectSPCompletedEventHandler GetSQLSelectSPCompleted;
        
        /// <remarks/>
        public event GetSQLSelectDataSetCompletedEventHandler GetSQLSelectDataSetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetSQLSelect", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLSelectResult GetSQLSelect(string FacultyName) {
            object[] results = this.Invoke("GetSQLSelect", new object[] {
                        FacultyName});
            return ((SQLSelectResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQLSelectAsync(string FacultyName) {
            this.GetSQLSelectAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetSQLSelectAsync(string FacultyName, object userState) {
            if ((this.GetSQLSelectOperationCompleted == null)) {
                this.GetSQLSelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQLSelectOperationCompleted);
            }
            this.InvokeAsync("GetSQLSelect", new object[] {
                        FacultyName}, this.GetSQLSelectOperationCompleted, userState);
        }
        
        private void OnGetSQLSelectOperationCompleted(object arg) {
            if ((this.GetSQLSelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQLSelectCompleted(this, new GetSQLSelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetSQLSelectSP", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SQLSelectResult GetSQLSelectSP(string FacultyName) {
            object[] results = this.Invoke("GetSQLSelectSP", new object[] {
                        FacultyName});
            return ((SQLSelectResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQLSelectSPAsync(string FacultyName) {
            this.GetSQLSelectSPAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetSQLSelectSPAsync(string FacultyName, object userState) {
            if ((this.GetSQLSelectSPOperationCompleted == null)) {
                this.GetSQLSelectSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQLSelectSPOperationCompleted);
            }
            this.InvokeAsync("GetSQLSelectSP", new object[] {
                        FacultyName}, this.GetSQLSelectSPOperationCompleted, userState);
        }
        
        private void OnGetSQLSelectSPOperationCompleted(object arg) {
            if ((this.GetSQLSelectSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQLSelectSPCompleted(this, new GetSQLSelectSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ieee.org/9780521712354/GetSQLSelectDataSet", RequestNamespace="http://www.ieee.org/9780521712354/", ResponseNamespace="http://www.ieee.org/9780521712354/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSQLSelectDataSet(string FacultyName) {
            object[] results = this.Invoke("GetSQLSelectDataSet", new object[] {
                        FacultyName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSQLSelectDataSetAsync(string FacultyName) {
            this.GetSQLSelectDataSetAsync(FacultyName, null);
        }
        
        /// <remarks/>
        public void GetSQLSelectDataSetAsync(string FacultyName, object userState) {
            if ((this.GetSQLSelectDataSetOperationCompleted == null)) {
                this.GetSQLSelectDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSQLSelectDataSetOperationCompleted);
            }
            this.InvokeAsync("GetSQLSelectDataSet", new object[] {
                        FacultyName}, this.GetSQLSelectDataSetOperationCompleted, userState);
        }
        
        private void OnGetSQLSelectDataSetOperationCompleted(object arg) {
            if ((this.GetSQLSelectDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSQLSelectDataSetCompleted(this, new GetSQLSelectDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class SQLSelectResult : SQLSelectBase {
        
        private string facultyIDField;
        
        private string facultyOfficeField;
        
        private string facultyPhoneField;
        
        private string facultyCollegeField;
        
        private string facultyTitleField;
        
        private string facultyEmailField;
        
        /// <remarks/>
        public string FacultyID {
            get {
                return this.facultyIDField;
            }
            set {
                this.facultyIDField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyOffice {
            get {
                return this.facultyOfficeField;
            }
            set {
                this.facultyOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyPhone {
            get {
                return this.facultyPhoneField;
            }
            set {
                this.facultyPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyCollege {
            get {
                return this.facultyCollegeField;
            }
            set {
                this.facultyCollegeField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyTitle {
            get {
                return this.facultyTitleField;
            }
            set {
                this.facultyTitleField = value;
            }
        }
        
        /// <remarks/>
        public string FacultyEmail {
            get {
                return this.facultyEmailField;
            }
            set {
                this.facultyEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQLSelectResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ieee.org/9780521712354/")]
    public partial class SQLSelectBase {
        
        private bool sQLRequestOKField;
        
        private string sQLRequestErrorField;
        
        /// <remarks/>
        public bool SQLRequestOK {
            get {
                return this.sQLRequestOKField;
            }
            set {
                this.sQLRequestOKField = value;
            }
        }
        
        /// <remarks/>
        public string SQLRequestError {
            get {
                return this.sQLRequestErrorField;
            }
            set {
                this.sQLRequestErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSQLSelectCompletedEventHandler(object sender, GetSQLSelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQLSelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQLSelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLSelectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLSelectResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSQLSelectSPCompletedEventHandler(object sender, GetSQLSelectSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQLSelectSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQLSelectSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SQLSelectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SQLSelectResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetSQLSelectDataSetCompletedEventHandler(object sender, GetSQLSelectDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSQLSelectDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSQLSelectDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591