//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSE_DEPTModel", "FK_Course_Faculty", "Faculty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSE_DEPTModel.Faculty), "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSE_DEPTModel.Course))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSE_DEPTModel", "FK_StudentCourse_Course", "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSE_DEPTModel.Course), "StudentCourse", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSE_DEPTModel.StudentCourse))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSE_DEPTModel", "FK_LogIn_Faculty", "Faculty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSE_DEPTModel.Faculty), "LogIn", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSE_DEPTModel.LogIn))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSE_DEPTModel", "FK_LogIn_Student", "Student", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSE_DEPTModel.Student), "LogIn", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSE_DEPTModel.LogIn))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CSE_DEPTModel", "FK_StudentCourse_Student", "Student", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSE_DEPTModel.Student), "StudentCourse", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSE_DEPTModel.StudentCourse))]

// Original file name:
// Generation date: 6/25/2008 11:38:37 AM
namespace CSE_DEPTModel
{
    
    /// <summary>
    /// There are no comments for EDModelEntitiesConnString in the schema.
    /// </summary>
    public partial class EDModelEntitiesConnString : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new EDModelEntitiesConnString object using the connection string found in the 'EDModelEntitiesConnString' section of the application configuration file.
        /// </summary>
        public EDModelEntitiesConnString() : 
                base("name=EDModelEntitiesConnString", "EDModelEntitiesConnString")
        {
        }
        /// <summary>
        /// Initialize a new EDModelEntitiesConnString object.
        /// </summary>
        public EDModelEntitiesConnString(string connectionString) : 
                base(connectionString, "EDModelEntitiesConnString")
        {
        }
        /// <summary>
        /// Initialize a new EDModelEntitiesConnString object.
        /// </summary>
        public EDModelEntitiesConnString(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EDModelEntitiesConnString")
        {
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Course> Course
        {
            get
            {
                if ((this._Course == null))
                {
                    this._Course = base.CreateQuery<Course>("[Course]");
                }
                return this._Course;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Course> _Course;
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Faculty> Faculty
        {
            get
            {
                if ((this._Faculty == null))
                {
                    this._Faculty = base.CreateQuery<Faculty>("[Faculty]");
                }
                return this._Faculty;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Faculty> _Faculty;
        /// <summary>
        /// There are no comments for LogIn in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<LogIn> LogIn
        {
            get
            {
                if ((this._LogIn == null))
                {
                    this._LogIn = base.CreateQuery<LogIn>("[LogIn]");
                }
                return this._LogIn;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LogIn> _LogIn;
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Student> Student
        {
            get
            {
                if ((this._Student == null))
                {
                    this._Student = base.CreateQuery<Student>("[Student]");
                }
                return this._Student;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Student> _Student;
        /// <summary>
        /// There are no comments for StudentCourse in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<StudentCourse> StudentCourse
        {
            get
            {
                if ((this._StudentCourse == null))
                {
                    this._StudentCourse = base.CreateQuery<StudentCourse>("[StudentCourse]");
                }
                return this._StudentCourse;
            }
        }
        private global::System.Data.Objects.ObjectQuery<StudentCourse> _StudentCourse;
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        public void AddToCourse(Course course)
        {
            base.AddObject("Course", course);
        }
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        public void AddToFaculty(Faculty faculty)
        {
            base.AddObject("Faculty", faculty);
        }
        /// <summary>
        /// There are no comments for LogIn in the schema.
        /// </summary>
        public void AddToLogIn(LogIn logIn)
        {
            base.AddObject("LogIn", logIn);
        }
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }
        /// <summary>
        /// There are no comments for StudentCourse in the schema.
        /// </summary>
        public void AddToStudentCourse(StudentCourse studentCourse)
        {
            base.AddObject("StudentCourse", studentCourse);
        }
    }
    /// <summary>
    /// There are no comments for CSE_DEPTModel.Course in the schema.
    /// </summary>
    /// <KeyProperties>
    /// course_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CSE_DEPTModel", Name="Course")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Course : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="course_id">Initial value of course_id.</param>
        public static Course CreateCourse(string course_id)
        {
            Course course = new Course();
            course.course_id = course_id;
            return course;
        }
        /// <summary>
        /// There are no comments for Property course_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string course_id
        {
            get
            {
                return this._course_id;
            }
            set
            {
                this.Oncourse_idChanging(value);
                this.ReportPropertyChanging("course_id");
                this._course_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("course_id");
                this.Oncourse_idChanged();
            }
        }
        private string _course_id;
        partial void Oncourse_idChanging(string value);
        partial void Oncourse_idChanged();
        /// <summary>
        /// There are no comments for Property course1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string course1
        {
            get
            {
                return this._course1;
            }
            set
            {
                this.Oncourse1Changing(value);
                this.ReportPropertyChanging("course1");
                this._course1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("course1");
                this.Oncourse1Changed();
            }
        }
        private string _course1;
        partial void Oncourse1Changing(string value);
        partial void Oncourse1Changed();
        /// <summary>
        /// There are no comments for Property credit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> credit
        {
            get
            {
                return this._credit;
            }
            set
            {
                this.OncreditChanging(value);
                this.ReportPropertyChanging("credit");
                this._credit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("credit");
                this.OncreditChanged();
            }
        }
        private global::System.Nullable<double> _credit;
        partial void OncreditChanging(global::System.Nullable<double> value);
        partial void OncreditChanged();
        /// <summary>
        /// There are no comments for Property classroom in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string classroom
        {
            get
            {
                return this._classroom;
            }
            set
            {
                this.OnclassroomChanging(value);
                this.ReportPropertyChanging("classroom");
                this._classroom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("classroom");
                this.OnclassroomChanged();
            }
        }
        private string _classroom;
        partial void OnclassroomChanging(string value);
        partial void OnclassroomChanged();
        /// <summary>
        /// There are no comments for Property schedule in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string schedule
        {
            get
            {
                return this._schedule;
            }
            set
            {
                this.OnscheduleChanging(value);
                this.ReportPropertyChanging("schedule");
                this._schedule = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("schedule");
                this.OnscheduleChanged();
            }
        }
        private string _schedule;
        partial void OnscheduleChanging(string value);
        partial void OnscheduleChanged();
        /// <summary>
        /// There are no comments for Property enrollment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> enrollment
        {
            get
            {
                return this._enrollment;
            }
            set
            {
                this.OnenrollmentChanging(value);
                this.ReportPropertyChanging("enrollment");
                this._enrollment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("enrollment");
                this.OnenrollmentChanged();
            }
        }
        private global::System.Nullable<int> _enrollment;
        partial void OnenrollmentChanging(global::System.Nullable<int> value);
        partial void OnenrollmentChanged();
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_Course_Faculty", "Faculty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Faculty Faculty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_Course_Faculty", "Faculty").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_Course_Faculty", "Faculty").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Faculty> FacultyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_Course_Faculty", "Faculty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Faculty>("CSE_DEPTModel.FK_Course_Faculty", "Faculty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for StudentCourse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_StudentCourse_Course", "StudentCourse")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<StudentCourse> StudentCourse
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<StudentCourse>("CSE_DEPTModel.FK_StudentCourse_Course", "StudentCourse");
            }
        }
    }
    /// <summary>
    /// There are no comments for CSE_DEPTModel.Faculty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// faculty_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CSE_DEPTModel", Name="Faculty")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Faculty : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Faculty object.
        /// </summary>
        /// <param name="faculty_id">Initial value of faculty_id.</param>
        public static Faculty CreateFaculty(string faculty_id)
        {
            Faculty faculty = new Faculty();
            faculty.faculty_id = faculty_id;
            return faculty;
        }
        /// <summary>
        /// There are no comments for Property faculty_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string faculty_id
        {
            get
            {
                return this._faculty_id;
            }
            set
            {
                this.Onfaculty_idChanging(value);
                this.ReportPropertyChanging("faculty_id");
                this._faculty_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("faculty_id");
                this.Onfaculty_idChanged();
            }
        }
        private string _faculty_id;
        partial void Onfaculty_idChanging(string value);
        partial void Onfaculty_idChanged();
        /// <summary>
        /// There are no comments for Property faculty_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string faculty_name
        {
            get
            {
                return this._faculty_name;
            }
            set
            {
                this.Onfaculty_nameChanging(value);
                this.ReportPropertyChanging("faculty_name");
                this._faculty_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("faculty_name");
                this.Onfaculty_nameChanged();
            }
        }
        private string _faculty_name;
        partial void Onfaculty_nameChanging(string value);
        partial void Onfaculty_nameChanged();
        /// <summary>
        /// There are no comments for Property office in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string office
        {
            get
            {
                return this._office;
            }
            set
            {
                this.OnofficeChanging(value);
                this.ReportPropertyChanging("office");
                this._office = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("office");
                this.OnofficeChanged();
            }
        }
        private string _office;
        partial void OnofficeChanging(string value);
        partial void OnofficeChanged();
        /// <summary>
        /// There are no comments for Property phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this.OnphoneChanging(value);
                this.ReportPropertyChanging("phone");
                this._phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("phone");
                this.OnphoneChanged();
            }
        }
        private string _phone;
        partial void OnphoneChanging(string value);
        partial void OnphoneChanged();
        /// <summary>
        /// There are no comments for Property college in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string college
        {
            get
            {
                return this._college;
            }
            set
            {
                this.OncollegeChanging(value);
                this.ReportPropertyChanging("college");
                this._college = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("college");
                this.OncollegeChanged();
            }
        }
        private string _college;
        partial void OncollegeChanging(string value);
        partial void OncollegeChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this.ReportPropertyChanging("title");
                this._title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("title");
                this.OntitleChanged();
            }
        }
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this.ReportPropertyChanging("email");
                this._email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("email");
                this.OnemailChanged();
            }
        }
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_Course_Faculty", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Course> Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Course>("CSE_DEPTModel.FK_Course_Faculty", "Course");
            }
        }
        /// <summary>
        /// There are no comments for LogIn in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_LogIn_Faculty", "LogIn")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<LogIn> LogIn
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LogIn>("CSE_DEPTModel.FK_LogIn_Faculty", "LogIn");
            }
        }
    }
    /// <summary>
    /// There are no comments for CSE_DEPTModel.LogIn in the schema.
    /// </summary>
    /// <KeyProperties>
    /// user_name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CSE_DEPTModel", Name="LogIn")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class LogIn : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LogIn object.
        /// </summary>
        /// <param name="user_name">Initial value of user_name.</param>
        public static LogIn CreateLogIn(string user_name)
        {
            LogIn logIn = new LogIn();
            logIn.user_name = user_name;
            return logIn;
        }
        /// <summary>
        /// There are no comments for Property user_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string user_name
        {
            get
            {
                return this._user_name;
            }
            set
            {
                this.Onuser_nameChanging(value);
                this.ReportPropertyChanging("user_name");
                this._user_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("user_name");
                this.Onuser_nameChanged();
            }
        }
        private string _user_name;
        partial void Onuser_nameChanging(string value);
        partial void Onuser_nameChanged();
        /// <summary>
        /// There are no comments for Property pass_word in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_word
        {
            get
            {
                return this._pass_word;
            }
            set
            {
                this.Onpass_wordChanging(value);
                this.ReportPropertyChanging("pass_word");
                this._pass_word = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("pass_word");
                this.Onpass_wordChanged();
            }
        }
        private string _pass_word;
        partial void Onpass_wordChanging(string value);
        partial void Onpass_wordChanged();
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_LogIn_Faculty", "Faculty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Faculty Faculty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_LogIn_Faculty", "Faculty").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_LogIn_Faculty", "Faculty").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Faculty in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Faculty> FacultyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Faculty>("CSE_DEPTModel.FK_LogIn_Faculty", "Faculty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Faculty>("CSE_DEPTModel.FK_LogIn_Faculty", "Faculty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_LogIn_Student", "Student")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Student Student
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_LogIn_Student", "Student").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_LogIn_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Student> StudentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_LogIn_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Student>("CSE_DEPTModel.FK_LogIn_Student", "Student", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CSE_DEPTModel.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// student_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CSE_DEPTModel", Name="Student")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Student : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="student_id">Initial value of student_id.</param>
        public static Student CreateStudent(string student_id)
        {
            Student student = new Student();
            student.student_id = student_id;
            return student;
        }
        /// <summary>
        /// There are no comments for Property student_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string student_id
        {
            get
            {
                return this._student_id;
            }
            set
            {
                this.Onstudent_idChanging(value);
                this.ReportPropertyChanging("student_id");
                this._student_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("student_id");
                this.Onstudent_idChanged();
            }
        }
        private string _student_id;
        partial void Onstudent_idChanging(string value);
        partial void Onstudent_idChanged();
        /// <summary>
        /// There are no comments for Property student_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string student_name
        {
            get
            {
                return this._student_name;
            }
            set
            {
                this.Onstudent_nameChanging(value);
                this.ReportPropertyChanging("student_name");
                this._student_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("student_name");
                this.Onstudent_nameChanged();
            }
        }
        private string _student_name;
        partial void Onstudent_nameChanging(string value);
        partial void Onstudent_nameChanged();
        /// <summary>
        /// There are no comments for Property gpa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> gpa
        {
            get
            {
                return this._gpa;
            }
            set
            {
                this.OngpaChanging(value);
                this.ReportPropertyChanging("gpa");
                this._gpa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("gpa");
                this.OngpaChanged();
            }
        }
        private global::System.Nullable<double> _gpa;
        partial void OngpaChanging(global::System.Nullable<double> value);
        partial void OngpaChanged();
        /// <summary>
        /// There are no comments for Property credits in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> credits
        {
            get
            {
                return this._credits;
            }
            set
            {
                this.OncreditsChanging(value);
                this.ReportPropertyChanging("credits");
                this._credits = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("credits");
                this.OncreditsChanged();
            }
        }
        private global::System.Nullable<int> _credits;
        partial void OncreditsChanging(global::System.Nullable<int> value);
        partial void OncreditsChanged();
        /// <summary>
        /// There are no comments for Property major in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string major
        {
            get
            {
                return this._major;
            }
            set
            {
                this.OnmajorChanging(value);
                this.ReportPropertyChanging("major");
                this._major = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("major");
                this.OnmajorChanged();
            }
        }
        private string _major;
        partial void OnmajorChanging(string value);
        partial void OnmajorChanged();
        /// <summary>
        /// There are no comments for Property schoolYear in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string schoolYear
        {
            get
            {
                return this._schoolYear;
            }
            set
            {
                this.OnschoolYearChanging(value);
                this.ReportPropertyChanging("schoolYear");
                this._schoolYear = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("schoolYear");
                this.OnschoolYearChanged();
            }
        }
        private string _schoolYear;
        partial void OnschoolYearChanging(string value);
        partial void OnschoolYearChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this.ReportPropertyChanging("email");
                this._email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("email");
                this.OnemailChanged();
            }
        }
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for LogIn in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_LogIn_Student", "LogIn")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<LogIn> LogIn
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LogIn>("CSE_DEPTModel.FK_LogIn_Student", "LogIn");
            }
        }
        /// <summary>
        /// There are no comments for StudentCourse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_StudentCourse_Student", "StudentCourse")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<StudentCourse> StudentCourse
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<StudentCourse>("CSE_DEPTModel.FK_StudentCourse_Student", "StudentCourse");
            }
        }
    }
    /// <summary>
    /// There are no comments for CSE_DEPTModel.StudentCourse in the schema.
    /// </summary>
    /// <KeyProperties>
    /// s_course_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CSE_DEPTModel", Name="StudentCourse")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class StudentCourse : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new StudentCourse object.
        /// </summary>
        /// <param name="s_course_id">Initial value of s_course_id.</param>
        public static StudentCourse CreateStudentCourse(int s_course_id)
        {
            StudentCourse studentCourse = new StudentCourse();
            studentCourse.s_course_id = s_course_id;
            return studentCourse;
        }
        /// <summary>
        /// There are no comments for Property s_course_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int s_course_id
        {
            get
            {
                return this._s_course_id;
            }
            set
            {
                this.Ons_course_idChanging(value);
                this.ReportPropertyChanging("s_course_id");
                this._s_course_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("s_course_id");
                this.Ons_course_idChanged();
            }
        }
        private int _s_course_id;
        partial void Ons_course_idChanging(int value);
        partial void Ons_course_idChanged();
        /// <summary>
        /// There are no comments for Property credit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> credit
        {
            get
            {
                return this._credit;
            }
            set
            {
                this.OncreditChanging(value);
                this.ReportPropertyChanging("credit");
                this._credit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("credit");
                this.OncreditChanged();
            }
        }
        private global::System.Nullable<int> _credit;
        partial void OncreditChanging(global::System.Nullable<int> value);
        partial void OncreditChanged();
        /// <summary>
        /// There are no comments for Property major in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string major
        {
            get
            {
                return this._major;
            }
            set
            {
                this.OnmajorChanging(value);
                this.ReportPropertyChanging("major");
                this._major = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("major");
                this.OnmajorChanged();
            }
        }
        private string _major;
        partial void OnmajorChanging(string value);
        partial void OnmajorChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_StudentCourse_Course", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Course Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("CSE_DEPTModel.FK_StudentCourse_Course", "Course").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("CSE_DEPTModel.FK_StudentCourse_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Course> CourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("CSE_DEPTModel.FK_StudentCourse_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Course>("CSE_DEPTModel.FK_StudentCourse_Course", "Course", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CSE_DEPTModel", "FK_StudentCourse_Student", "Student")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Student Student
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_StudentCourse_Student", "Student").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_StudentCourse_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Student> StudentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("CSE_DEPTModel.FK_StudentCourse_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Student>("CSE_DEPTModel.FK_StudentCourse_Student", "Student", value);
                }
            }
        }
    }
}
